### PR TITLE
Track xml-rs changes

### LINKED ISSUE #16: Build breakage because of xml-rs change
The build is broken because xml-rs added a new field to its config (in https://github.com/netvl/xml-rs/commit/03c7c3e746cd524f6d50c6007abd13f7989fffa3).

    error[E0063]: missing field `extra_entities` in initializer of `xml_rs::ParserConfig`
      --> src/xml/reader.rs:25:22
       |
    25 |         let config = ParserConfig {
       |                      ^^^^^^^^^^^^ missing `extra_entities`

Arguably, the xml-rs change did not follow semver, they should have bumped minor. In any case, looks like the fix is to add an empty hashmap.

### PR DESCRIPTION
**Pull request by raphlinus**
A recent release of xml-rs (0.3.7) added a new field to the parser
config. This patch provides that field and also updates the version.

Fixes #16

### CODE REVIEW

**Comment by raphlinus** [comment]
A case can be made that this code should be changed to use the builder-like pattern suggested in the xml-rs documentation, which would protect against future additional fields. Would you rather see that change?

**Comment by drahnr** [comment]
Is there a reason this is still open?

Currently `snytect` is broken and this fixes it. At least short term wise this should be merged.

**Comment by ebarnard** [comment]
Thanks. I'll release an update using the builder pattern.
