### ISSUE TITLE
Build breakage because of xml-rs change

### ISSUE THREAD

**Issue by raphlinus** [ebarnard/rust-plist#16]
The build is broken because xml-rs added a new field to its config (in https://github.com/netvl/xml-rs/commit/03c7c3e746cd524f6d50c6007abd13f7989fffa3).

    error[E0063]: missing field `extra_entities` in initializer of `xml_rs::ParserConfig`
      --> src/xml/reader.rs:25:22
       |
    25 |         let config = ParserConfig {
       |                      ^^^^^^^^^^^^ missing `extra_entities`

Arguably, the xml-rs change did not follow semver, they should have bumped minor. In any case, looks like the fix is to add an empty hashmap.

**Comment by ebarnard** [comment]
Fixed in 0.1.1.
